### ISSUE TITLE
Will source code be released ?

### ISSUE THREAD

**Issue by kpup1710** [jinga-lala/DAMEX#1]
When will the source code of the paper be released? It's 2024 already.

**Comment by hongge831** [comment]
@jinga-lala When will the source code of the paper be released? It's 2024 already.

**Comment by supertyd** [comment]
so code is what i need , I just want to know the loss setting  . Thanks

**Comment by jinga-lala** [comment]
Code have been released. Extremely sorry for the delay and thank you for your interest in DAMEX.

@supertyd The loss setting can be found in [moe.py](https://github.com/jinga-lala/DAMEX/blob/main/models/dino/moe.py).
